apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cv-app-pipeline
description: Pipeline for CV application deployment
serialPipeline:
  stages:
  - targetId: dev
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Development environment
gke:
  cluster: projects/PROJECT_ID/locations/REGION/clusters/cv-app-cluster