apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-app
  template:
    metadata:
      labels:
        app: cv-app
    spec:
      containers:
      - name: cv-app
        image: gcr.io/PROJECT_ID/cv-app:COMMIT_SHA
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10